version: "3.9"

services:

  ontrack-api-db:
    image: mysql:8.0-oracle
    container_name: ontrack-api-db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ontrack_db
    volumes:
      - ./db-data/ontrack:/var/lib/mysql

  ontrack-api:
    image: ontrackspringapi
    container_name: ontrack-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ontrack-api-db:3306/ontrack_db?connectTimeout=0&socketTimeout=0&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8094:8080"